server:
  port: 8081
spring:
  application:
    name: catalog-service
management:
  endpoints:
    web:
      exposure:
        include: *
eureka:
  client:
    healthcheck:
      enabled=: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}