server:
  port: 8084

spring:
  application:
    name: comments-service
  data:
    mongodb:
      host: localhost
      port: 27017
      database: comments-db

management:
  endpoints:
    web:
      exposure:
        include: '*'
eureka:
  client:
    healthcheck:
      enabled=: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}