server:
  port: 8083

spring:
  application:
    name: ratings-service
  data:
    mongodb:
      host: localhost
      port: 27017
      database: ratings-db

management:
  endpoints:
    web:
      exposure:
        include: '*'
eureka:
  client:
    healthcheck:
      enabled=: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}